Repository dgiot/dgiot, pull requests merged in 2022-08, with the labels that each got.

#507 Guo
  apps/dgiot_factory/include/dgiot_factory.hrl
  apps/dgiot_factory/priv/json/test
  apps/dgiot_factory/priv/json/womoxing.json
  apps/dgiot_factory/priv/swagger/swagger_factory.json
  apps/dgiot_factory/src/dgiot_factory_calendar.erl
  apps/dgiot_factory/src/dgiot_factory_channel.erl
  apps/dgiot_factory/src/dgiot_factory_data.erl
  apps/dgiot_factory/src/dgiot_factory_getdata.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_meter.erl
  apps/dgiot_factory/src/dgiot_factory_shift.erl
  apps/dgiot_factory/src/dgiot_factory_utils.erl
Labels: Extra Large

#509 fix:factory_channel
  apps/dgiot_factory/src/dgiot_factory_channel.erl
Labels: Extra Small

#510 fix:factory
  apps/dgiot_factory/priv/swagger/swagger_factory.json
  apps/dgiot_factory/src/dgiot_factory_data.erl
  apps/dgiot_factory/src/dgiot_factory_getdata.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_shift.erl
Labels: Extra Small

#536 fix:factory
  apps/dgiot/src/utils/dgiot_datetime.erl
  apps/dgiot_dlink/src/bridge/dgiot_tcp2dlink_channel.erl
  apps/dgiot_dlink/src/bridge/dgiot_tcp2dlink_worker.erl
  apps/dgiot_factory/conf/dgiot_parse.conf
  apps/dgiot_factory/src/dgiot_factory_app.erl
  apps/dgiot_factory/src/dgiot_factory_channel.erl
  apps/dgiot_factory/src/dgiot_factory_getdata.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_utils.erl
  apps/dgiot_tdengine/src/utils/dgiot_tdengine_field.erl
Labels: Large

#538 fix:tcp2dlink
  apps/dgiot_dlink/src/bridge/dgiot_tcp2dlink_worker.erl
Labels: Medium

#540 fix:factory
  apps/dgiot/src/utils/dgiot_map.erl
  apps/dgiot_dlink/src/bridge/dgiot_tcp2dlink_worker.erl
  apps/dgiot_factory/include/dgiot_factory.hrl
  apps/dgiot_factory/priv/swagger/swagger_factory.json
  apps/dgiot_factory/src/dgiot_factory_calendar.erl
  apps/dgiot_factory/src/dgiot_factory_channel.erl
  apps/dgiot_factory/src/dgiot_factory_getdata.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_shift.erl
  apps/dgiot_factory/src/dgiot_factory_utils.erl
Labels: Extra Large

#544 fix:online_status
  apps/dgiot_dlink/src/proctol/dgiot_mqtt_auth.erl
  apps/dgiot_modbus/src/dgiot_modbusrtu_tcp.erl
Labels: Extra Small

#547 feat: add factory_material
  apps/dgiot_factory/src/dgiot_factory_material.erl
Labels: Small

#550 Restyled/guo
  apps/dgiot_factory/priv/swagger/swagger_factory.json
  apps/dgiot_factory/src/dgiot_factory_calendar.erl
  apps/dgiot_factory/src/dgiot_factory_getdata.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_utils.erl
Labels: Large

#553 Restyled/guo
  apps/dgiot_factory/src/dgiot_factory_calendar.erl
  apps/dgiot_factory/src/dgiot_factory_data.erl
Labels: Extra Small

#554 数字工厂，短信告警
  README-CN.md
  apps/dgiot/src/utils/dgiot_datetime.erl
  apps/dgiot/src/utils/dgiot_map.erl
  apps/dgiot_api/priv/swagger/swagger_data.json
  apps/dgiot_api/src/handler/dgiot_data_handler.erl
  apps/dgiot_bridge/priv/swagger/swagger_bridge.json
  apps/dgiot_bridge/src/dgiot_bridge.erl
  apps/dgiot_bridge/src/dgiot_bridge_app.erl
  apps/dgiot_bridge/src/handler/dgiot_bridge_handler.erl
  apps/dgiot_device/src/dgiot_notification_channel.erl
  apps/dgiot_dlink/README.md
  apps/dgiot_dlink/src/bridge/dgiot_tcp2dlink_channel.erl
  apps/dgiot_dlink/src/bridge/dgiot_tcp2dlink_worker.erl
  apps/dgiot_dlink/src/proctol/dgiot_mqtt_acl.erl
  apps/dgiot_dlink/src/proctol/dgiot_mqtt_auth.erl
  apps/dgiot_dlink/src/proctol/dgiot_mqtt_message.erl
  apps/dgiot_evidence/src/handler/dgiot_evidence_handler.erl
  apps/dgiot_factory/conf/dgiot_parse.conf
  apps/dgiot_factory/include/dgiot_factory.hrl
  apps/dgiot_factory/priv/json/test
  apps/dgiot_factory/priv/json/womoxing.json
  apps/dgiot_factory/priv/swagger/swagger_factory.json
  apps/dgiot_factory/src/dgiot_factory_app.erl
  apps/dgiot_factory/src/dgiot_factory_calendar.erl
  apps/dgiot_factory/src/dgiot_factory_channel.erl
  apps/dgiot_factory/src/dgiot_factory_data.erl
  apps/dgiot_factory/src/dgiot_factory_getdata.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_meter.erl
  apps/dgiot_factory/src/dgiot_factory_shift.erl
  apps/dgiot_factory/src/dgiot_factory_utils.erl
  apps/dgiot_http/etc/dgiot_http.conf
  apps/dgiot_http/priv/dgiot_http.schema
  apps/dgiot_http/priv/swagger/swagger_http.json
  apps/dgiot_http/src/dgiot_http_handler.erl
  apps/dgiot_http/src/umeng/dgiot_notification.erl
  apps/dgiot_http/src/umeng/dgiot_umeng.erl
  apps/dgiot_modbus/src/dgiot_modbusc_channel.erl
  apps/dgiot_modbus/src/dgiot_modbusrtu_tcp.erl
  apps/dgiot_parse/etc/dgiot_parse.conf
  apps/dgiot_tdengine/src/dgiot_tdengine_channel.erl
  apps/dgiot_tdengine/src/utils/dgiot_tdengine_field.erl
Labels: Extra Large

#563 fix:factory
  apps/dgiot_factory/include/dgiot_factory.hrl
  apps/dgiot_factory/priv/swagger/swagger_factory.json
  apps/dgiot_factory/src/dgiot_factory_app.erl
  apps/dgiot_factory/src/dgiot_factory_calendar.erl
  apps/dgiot_factory/src/dgiot_factory_data.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_material.erl
Labels: Large

#570 磐安工厂2
  apps/dgiot_http/priv/swagger/swagger_http.json
  apps/dgiot_http/src/dgiot_http_handler.erl
Labels: Extra Small

#574 数字工厂
  apps/dgiot_http/priv/swagger/swagger_http.json
  apps/dgiot_http/src/dgiot_http_handler.erl
Labels: Extra Small

#578 工厂
  apps/dgiot_http/src/dgiot_http_handler.erl
Labels: Extra Small

#580 fix:factory
  apps/dgiot_factory/src/dgiot_factory_app.erl
  apps/dgiot_factory/src/dgiot_factory_getdata.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_material.erl
  apps/dgiot_factory/src/dgiot_factory_shift.erl
Labels: Large

#583 工厂
  apps/dgiot_http/etc/dgiot_http.conf
  apps/dgiot_http/priv/dgiot_http.schema
  apps/dgiot_http/priv/swagger/swagger_http.json
  apps/dgiot_http/src/dgiot_http_handler.erl
  apps/dgiot_http/src/umeng/dgiot_notification.erl
Labels: Small

#600 fix:factory
  apps/dgiot_factory/include/dgiot_factory.hrl
  apps/dgiot_factory/priv/swagger/swagger_factory.json
  apps/dgiot_factory/src/dgiot_factory_app.erl
  apps/dgiot_factory/src/dgiot_factory_getdata.erl
  apps/dgiot_factory/src/dgiot_factory_handler.erl
  apps/dgiot_factory/src/dgiot_factory_material.erl
  apps/dgiot_factory/src/dgiot_factory_shift.erl
  apps/dgiot_factory/src/dgiot_factory_utils.erl
Labels: Extra Large
